/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.SupplierBillinRole;

import EcoSystem.EcoSystem;
import EcoSystem.Enterprise.Amazon;
import EcoSystem.Enterprise.Enterprise;
import EcoSystem.Enterprise.Supplier;
import EcoSystem.Network.Network;
import EcoSystem.Order.Invoice;
import EcoSystem.Order.Order;
import EcoSystem.UserAccount.UserAccount;
import EcoSystem.WorkQueue.InvoiceGenerationRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Mustansir
 */
public class GenerateInvoiceJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Amazon amazon;
    private Supplier supplier;
    private InvoiceGenerationRequest ivr;
    private EcoSystem ecoSystem;
    private UserAccount userAccount;
    public GenerateInvoiceJPanel(JPanel upc , Supplier supplier , InvoiceGenerationRequest ivr, EcoSystem ecoSystem , UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = upc;
        this.supplier = supplier;
        this.ivr = ivr;
        this.ecoSystem = ecoSystem;
        this.userAccount = userAccount;
        
        
        for(Network countryNetwork : ecoSystem.getNetworkDirectory().getNetworkList()){
            if(countryNetwork.getName().equals(supplier.getAddress().getCountry())){
                for(Enterprise enterprise : countryNetwork.getEnterpriseDirectory().getEnterpriseList()){
                    if(enterprise instanceof Amazon){
                        this.amazon = (Amazon)enterprise;
                    }
                }
            }
        }
        populateForm();
    }
    private void populateForm(){
        customerSalepirceTxt.setText(String.valueOf(ivr.getOrderItem().Price()));
        double cost = ivr.getOrderItem().Price();
        double Commission = (cost *10)/100;
        double finalvalue = (cost-Commission);
        amazonCommisiontxt.setText(String.valueOf(Commission));
        invoiceAmountTxt.setText(String.valueOf(finalvalue));
        
        Order order = new Order();
        order.addOrderItem(ivr.getOrderItem());
        Invoice invoice = amazon.getSupplierInvoiceDirectory().createandAddInvoice();
        invoice.setOrder(order);
        invoice.setTax(0);
        invoice.setTotal(Double.parseDouble(invoiceAmountTxt.getText()));
        supplier.getInvoiceDirectory().AddInvoice(invoice);
        ivr.setGenerated(true);
        ivr.setReceiver(userAccount);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        customerSalepirceTxt = new javax.swing.JTextField();
        amazonCommisiontxt = new javax.swing.JTextField();
        invoiceAmountTxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        jLabel1.setText("Customer Sale Price :");

        jLabel2.setText("Amazon's Commision :");

        jLabel3.setText("Invoice Ammount :");

        customerSalepirceTxt.setEditable(false);

        amazonCommisiontxt.setEditable(false);

        invoiceAmountTxt.setEditable(false);

        jButton1.setText("Generate and Send Invoice");

        backButton.setText("<< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(customerSalepirceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(amazonCommisiontxt)
                                    .addComponent(invoiceAmountTxt)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(backButton)
                        .addGap(42, 42, 42)
                        .addComponent(jButton1)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(customerSalepirceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(amazonCommisiontxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(invoiceAmountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(backButton))
                .addContainerGap(141, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.remove(this);
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amazonCommisiontxt;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField customerSalepirceTxt;
    private javax.swing.JTextField invoiceAmountTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
