/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.SupplierBillinRole;

import EcoSystem.EcoSystem;
import EcoSystem.Enterprise.Supplier;
import EcoSystem.UserAccount.UserAccount;
import EcoSystem.WorkQueue.InvoiceGenerationRequest;
import EcoSystem.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mustansir
 */
public class SupplierBillingEmployeeWorkArea extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Supplier supplier;
    private UserAccount userAccount;
    private EcoSystem ecoSystem;
    
    public SupplierBillingEmployeeWorkArea(JPanel upc , Supplier supplier , UserAccount userAccount , EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = upc;
        this.supplier = supplier;
        this.userAccount = userAccount;
        this.ecoSystem = ecoSystem;
        populateInvoicetable();
    }
    
    private void populateInvoicetable(){
        DefaultTableModel model = (DefaultTableModel)invoicerequest.getModel();
        model.setRowCount(0);
        for(WorkRequest wr : supplier.getWorkQueue().getWorkQueueList()){
            if(wr instanceof InvoiceGenerationRequest){
                InvoiceGenerationRequest ivr =(InvoiceGenerationRequest)wr;
            Object[] row = new Object[5];
            row[0]=ivr;
            row[1]=ivr.getOrderItem().getProductInventory().getProduct().getProductPrice();
            row[2]=ivr.getOrderItem().getQuantity();
            row[3]=ivr.isGenerated() == false ? "Pending" : "Invoice Sent";
            row[4]=ivr.getReceiver() == null ? "Not Assigned" : ivr.getReceiver();
            model.addRow(row);
            }
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        invoicerequest = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        invoicerequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Product", "Quantity", "Price", "Invoice status", "Invoice Generated By"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(invoicerequest);

        jButton1.setText("Generate Invoice");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(145, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int selectRow = invoicerequest.getSelectedRow();
        if(selectRow < 0){
            JOptionPane.showMessageDialog(null, "Please select an invoice ");
            return;
        }
        InvoiceGenerationRequest ivr = (InvoiceGenerationRequest)invoicerequest.getValueAt(selectRow, 0);
        if(ivr.isGenerated()){
            JOptionPane.showMessageDialog(null, "The invoice has been generated ");
           return;
        }
        GenerateInvoiceJPanel generateInvoiceJPanel = new GenerateInvoiceJPanel(userProcessContainer, supplier, ivr, ecoSystem, userAccount);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.add("Invoice generation",generateInvoiceJPanel);
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        populateInvoicetable();
    }//GEN-LAST:event_formComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable invoicerequest;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
