/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.SupplierRole;

import EcoSystem.EcoSystem;
import EcoSystem.Enterprise.Supplier;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Mustansir
 */
public class ManageOrganizationJPanel extends javax.swing.JPanel {

    private Supplier supplier;
    private JPanel userProcessContainer;
    private EcoSystem ecoSystem;
            
    
    
    public ManageOrganizationJPanel(Supplier supplier , JPanel upc , EcoSystem ecoSystem) {
        initComponents();
        this.supplier = supplier;
        this.userProcessContainer = upc;
        this.ecoSystem = ecoSystem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createOrganizationJButton = new javax.swing.JButton();
        createOrganizationEmployeeJButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        createOrganizationJButton.setText("Create Organization");
        createOrganizationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createOrganizationJButtonActionPerformed(evt);
            }
        });

        createOrganizationEmployeeJButton.setText("Create Organization Employee");
        createOrganizationEmployeeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createOrganizationEmployeeJButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Create Admin UserAccount");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(createOrganizationJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createOrganizationEmployeeJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(createOrganizationJButton)
                .addGap(27, 27, 27)
                .addComponent(createOrganizationEmployeeJButton)
                .addGap(29, 29, 29)
                .addComponent(jButton2)
                .addContainerGap(107, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createOrganizationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createOrganizationJButtonActionPerformed
        CreateOrganizationJPanel cojp = new CreateOrganizationJPanel(supplier, userProcessContainer);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.add("Create organization", cojp);
        layout.next(userProcessContainer);
    }//GEN-LAST:event_createOrganizationJButtonActionPerformed

    private void createOrganizationEmployeeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createOrganizationEmployeeJButtonActionPerformed
        CreateOrganizationEmployeeJPanel coejp = new CreateOrganizationEmployeeJPanel(ecoSystem, userProcessContainer, supplier);
         CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.add("Create Employee" , coejp);
        layout.next(userProcessContainer);        
    }//GEN-LAST:event_createOrganizationEmployeeJButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ManageUserAccountJPanel manageUserAccountJPanel = new ManageUserAccountJPanel(supplier, userProcessContainer, ecoSystem);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.add("ManageUserAccount " , manageUserAccountJPanel);
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createOrganizationEmployeeJButton;
    private javax.swing.JButton createOrganizationJButton;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
