/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.SupplierRole;

import EcoSystem.EcoSystem;
import EcoSystem.Enterprise.Amazon;
import EcoSystem.Enterprise.Enterprise;
import EcoSystem.Enterprise.Supplier;
import EcoSystem.GeoConverting.AddressConverter;
import EcoSystem.Network.Network;
import EcoSystem.Person.Address;
import EcoSystem.WorkQueue.SupplierRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.text.JTextComponent;

/**
 *
 * @author Mustansir
 */
public class NewSupplierJPanel extends javax.swing.JPanel {

    private EcoSystem ecoSystem;
    private JPanel userProcessContainer;
    
    public NewSupplierJPanel(EcoSystem ecoSystem , JPanel upc) {
        initComponents();
        this.ecoSystem = ecoSystem;
        this.userProcessContainer = upc;
        populateCountryCombo();
        requestJLabel.setVisible(false);
        requestIdTxtField.setVisible(false);
        requestIdTxtField.setText("0");
        
    }
    public void populateCountryCombo(){
        CountryJcomboBox.removeAllItems();
        for(Network countryNetwork : ecoSystem.getNetworkDirectory().getNetworkList()){
            CountryJcomboBox.addItem(countryNetwork);
        }
    }
    
    public void populatestateCombo(){
        Network countryNetwork = (Network)CountryJcomboBox.getSelectedItem();
        if(countryNetwork == null){
            return;
        }
       
       
        
        stateComboBox.removeAllItems();
        for(Network stateNetwork : countryNetwork.getNetworkDirectory().getNetworkList()){
            stateComboBox.addItem(stateNetwork);
        }
    }
    
    public void populatecityCombo(){
        Network stateNetwork = (Network)stateComboBox.getSelectedItem();
        if(stateNetwork == null){
            return;
        }
        cityComboBox.removeAllItems();
        for(Network cityNetwork : stateNetwork.getNetworkDirectory().getNetworkList()){
            cityComboBox.addItem(cityNetwork);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        CountryTxtField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        zipCodetxtField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        streetTxtField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        stateComboBox = new javax.swing.JComboBox();
        cityComboBox = new javax.swing.JComboBox();
        nameTxtField = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        CountryJcomboBox = new javax.swing.JComboBox();
        requestJButton = new javax.swing.JButton();
        requestJLabel = new javax.swing.JLabel();
        requestIdTxtField = new javax.swing.JTextField();

        jLabel13.setText("ZipCode");

        jLabel12.setText("Country");

        CountryTxtField.setEditable(false);

        jLabel11.setText("Please Provide Supplier Address");

        jLabel10.setText("State");

        jLabel9.setText("City");

        jLabel8.setText("Street Address:");

        stateComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        stateComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateComboBoxActionPerformed(evt);
            }
        });

        cityComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        backButton.setText("<< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Supplier Location:");

        jLabel14.setText("Name :");

        CountryJcomboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CountryJcomboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CountryJcomboBoxActionPerformed(evt);
            }
        });

        requestJButton.setText("Request");
        requestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestJButtonActionPerformed(evt);
            }
        });

        requestJLabel.setText("Your Request Id is :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CountryJcomboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel12))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(CountryTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(zipCodetxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(streetTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(stateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel11)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(requestJButton)))
                        .addGap(118, 118, 118)))
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(requestJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(requestIdTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CountryJcomboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(nameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(streetTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(stateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(CountryTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(zipCodetxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backButton)
                    .addComponent(requestJButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(requestJLabel)
                    .addComponent(requestIdTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void stateComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateComboBoxActionPerformed
        populatecityCombo();
    }//GEN-LAST:event_stateComboBoxActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
         userProcessContainer.removeAll();
        userProcessContainer.add(new JPanel());
       ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    private void CountryJcomboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CountryJcomboBoxActionPerformed
        Network n = (Network)CountryJcomboBox.getSelectedItem();
        if(n == null){
            return;
        }
        CountryTxtField.setText(n.getName());
        populatestateCombo();
    }//GEN-LAST:event_CountryJcomboBoxActionPerformed

    private void requestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestJButtonActionPerformed
        //gather Data
        try{
        Amazon amazon = null;
        Network countryNetwork =(Network) CountryJcomboBox.getSelectedItem();
        for(Enterprise enterprise : countryNetwork.getEnterpriseDirectory().getEnterpriseList()){
            if(enterprise.getEnterpriseType().equals(Enterprise.EnterpriseType.Amazon)){
                amazon = (Amazon)enterprise;
            }
        }
               
                      
        String name = nameTxtField.getText();
        String street = streetTxtField.getText();
        String city = String.valueOf(cityComboBox.getSelectedItem());
        String state = String.valueOf(stateComboBox.getSelectedItem());
        String country = CountryTxtField.getText();
        String zipcode = zipCodetxtField.getText();
        //validate form
        for (Component C : this.getComponents()){
            if (C instanceof JTextField  ){
                String text =((JTextComponent) C).getText();
                if(text.trim().isEmpty()){
                    JOptionPane.showMessageDialog(null, "Please Complete the form");
                    return;                    
                }
            }            
        }
        
        
        //create Request
        
            
            Address add = new Address();
        add.setStreetAddress(street);
        add.setCity(city);
        add.setState(state);
        add.setCountry(country);
        add.setZipCode(Integer.parseInt(zipcode));
        AddressConverter ac = new AddressConverter();
        add.setLatitude(Double.parseDouble(ac.calculatelatitude(String.valueOf(add))));
        add.setLongitude(Double.parseDouble(ac.calculateLongitude(String.valueOf(add))));
        Supplier supplier = new Supplier(name, add);
        SupplierRequest request = new SupplierRequest();
        request.setSupplier(supplier);      
        request.setMessage("New Supplier request");        
        amazon.getWorkQueue().getWorkQueueList().add(request);
        
        
        //Display request ID
      for (Component C : this.getComponents()){
            if (C instanceof JTextField || C instanceof JTextArea || C instanceof JComboBox  ){
                C.setEnabled(false);
               
            }            
        }
        requestJButton.setEnabled(false);
        
        requestJLabel.setVisible(true);
        requestIdTxtField.setVisible(true);
        requestIdTxtField.setText(String.valueOf(request.getRequestID()));
        }catch(NumberFormatException e ){JOptionPane.showMessageDialog(null, "Please Enter zipcode in numerical format only ");return;}
        

    }//GEN-LAST:event_requestJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CountryJcomboBox;
    private javax.swing.JTextField CountryTxtField;
    private javax.swing.JButton backButton;
    private javax.swing.JComboBox cityComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nameTxtField;
    private javax.swing.JTextField requestIdTxtField;
    private javax.swing.JButton requestJButton;
    private javax.swing.JLabel requestJLabel;
    private javax.swing.JComboBox stateComboBox;
    private javax.swing.JTextField streetTxtField;
    private javax.swing.JTextField zipCodetxtField;
    // End of variables declaration//GEN-END:variables
}
