/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface;

import EcoSystem.EcoSystem;
import UserInterface.CustomerRole.NewCustomerJPanel;
import UserInterface.SupplierRole.NewSupplierJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Mustansir
 */
public class SignUpJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem ecoSystem;
    public SignUpJPanel(EcoSystem ecoSystem , JPanel upc) {
        initComponents();
        this.ecoSystem = ecoSystem;
        this.userProcessContainer = upc;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NewCustomerJButton = new javax.swing.JButton();
        NewSupplierJButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        NewCustomerJButton.setText("New Customer ?");
        NewCustomerJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewCustomerJButtonActionPerformed(evt);
            }
        });

        NewSupplierJButton.setText("New Supplier ?");
        NewSupplierJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewSupplierJButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Check Supplier Status");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NewCustomerJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NewSupplierJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(NewCustomerJButton)
                .addGap(18, 18, 18)
                .addComponent(NewSupplierJButton)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(90, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void NewCustomerJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewCustomerJButtonActionPerformed
        NewCustomerJPanel newCustomerJPanel = new NewCustomerJPanel(userProcessContainer, ecoSystem);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.add("NewCustomer", newCustomerJPanel);
        layout.next(userProcessContainer);

    }//GEN-LAST:event_NewCustomerJButtonActionPerformed

    private void NewSupplierJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewSupplierJButtonActionPerformed
        NewSupplierJPanel supplierJPanel = new NewSupplierJPanel(ecoSystem, userProcessContainer);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.add("supplier", supplierJPanel);
        layout.next(userProcessContainer);
    }//GEN-LAST:event_NewSupplierJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NewCustomerJButton;
    private javax.swing.JButton NewSupplierJButton;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
