/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.CustomerRole;

import EcoSystem.Customer.Customer;
import EcoSystem.EcoSystem;
import EcoSystem.Enterprise.Amazon;
import EcoSystem.Enterprise.Supplier;
import EcoSystem.Order.Invoice;
import EcoSystem.Order.Order;
import EcoSystem.Order.OrderItem;
import EcoSystem.UserAccount.UserAccount;
import EcoSystem.WorkQueue.OrderRequest;
import EcoSystem.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.text.DecimalFormat;
import java.util.Date;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mustansir
 */
public class CheckoutJPanel extends javax.swing.JPanel {

    private Customer customer;
    private JPanel userProcessContainer;
    
    private EcoSystem ecoSystem;
    private Amazon amazon;
    private UserAccount userAccount;
    public CheckoutJPanel(Customer customer , JPanel upc , EcoSystem ecoSystem , Amazon amazon , UserAccount userAccount) {
        initComponents();
        this.customer = customer;
        this.userProcessContainer = upc ;
        this.ecoSystem = ecoSystem;
        this.amazon = amazon;
        this.userAccount = userAccount;
        populateCart();
        populateForm();
                
    }
    public void populateCart()
    {
        DefaultTableModel model = (DefaultTableModel)finalcheckoutJTable.getModel();
        model.setRowCount(0);
        
        for(OrderItem oi : customer.getCart().getOrderItemList()){
            Object[] row = new Object[6];
            row[0]=oi;
            row[1]=oi.getProductInventory().getProduct().getProductCompany();
            row[2]=oi.getProductInventory().getProduct().getProductPrice();
            row[3]=oi.getQuantity();
            row[4]=oi.Price();
            row[5]=oi.getProductInventory().getQuantity();
            model.addRow(row);
                    
        }
    }
    
    public void populateForm(){
        streetTxtfield.setText(customer.getPerson().getAddress().getStreetAddress());
        CityTxtField.setText(customer.getPerson().getAddress().getCity());
        StateTxtField.setText(customer.getPerson().getAddress().getState());
        countryTxtField.setText(customer.getPerson().getAddress().getCountry());
        zipCodetxtField.setText(String.valueOf(customer.getPerson().getAddress().getZipCode()));
        
        double  cost =0;
        for(OrderItem oi :customer.getCart().getOrderItemList()){
            cost +=oi.Price();
        }
        DecimalFormat df = new DecimalFormat("#.00");
        
        totalCosttxtField.setText(df.format(cost));
        double tax = cost * 0.065;
        
        taxTxtField.setText(String.valueOf(df.format(tax)));       
       
        double totolround = tax+cost;
        grandTotalTxtField.setText(String.valueOf(df.format(totolround)));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        CheckoutCartTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        finalcheckoutJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        streetTxtfield = new javax.swing.JTextField();
        CityTxtField = new javax.swing.JTextField();
        StateTxtField = new javax.swing.JTextField();
        countryTxtField = new javax.swing.JTextField();
        zipCodetxtField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        totalCosttxtField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        taxTxtField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        grandTotalTxtField = new javax.swing.JTextField();
        checkOutJButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        CheckoutCartTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Product Name", "ProductCompany", "ProductPrice", "Quantity", "Price", "Stock Remaining"
            }
        ));
        jScrollPane1.setViewportView(CheckoutCartTable);

        finalcheckoutJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Product Name", "ProductCompany", "ProductPrice", "Quantity", "Price", "Stock Remaining"
            }
        ));
        jScrollPane2.setViewportView(finalcheckoutJTable);

        jLabel1.setText("Delivery Address :");

        jLabel2.setText("Street :");

        jLabel3.setText("City");

        jLabel4.setText("State :");

        jLabel5.setText("Country :");

        jLabel6.setText("ZipCode :");

        streetTxtfield.setEditable(false);

        CityTxtField.setEditable(false);

        StateTxtField.setEditable(false);

        countryTxtField.setEditable(false);

        zipCodetxtField.setEditable(false);

        jLabel7.setText("Sub Total :");

        totalCosttxtField.setEditable(false);

        jLabel8.setText("Tax @ 6.5 % :");

        taxTxtField.setEditable(false);

        jLabel10.setText("GrandTotal");

        grandTotalTxtField.setEditable(false);

        checkOutJButton.setText("CheckOut");
        checkOutJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutJButtonActionPerformed(evt);
            }
        });

        backButton.setText("<< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(StateTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CityTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(streetTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(countryTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(zipCodetxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(92, 92, 92)
                                        .addComponent(jLabel7))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalCosttxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(taxTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grandTotalTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(backButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(checkOutJButton)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7)
                    .addComponent(totalCosttxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(streetTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(taxTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CityTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(StateTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(countryTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10)
                    .addComponent(grandTotalTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(zipCodetxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(checkOutJButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void checkOutJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutJButtonActionPerformed
        
        Invoice invoice =amazon.getCustomerInvoiceDirectory().createandAddInvoice();
        invoice.setCustomer(customer);
        Order order = new Order();
        for(OrderItem oi : customer.getCart().getOrderItemList()){
            order.addOrderItem(oi);
        }
        invoice.setOrder(order);     
        invoice.setTotal(Double.parseDouble(grandTotalTxtField.getText()));
        invoice.setTax(Double.parseDouble(taxTxtField.getText()));
        Invoice invoice1 =customer.getInvoiceDirectory().AddInvoice(invoice);
        
        
        amazon.getMasterOrderList().addOrder(order);
        amazon.getCustomerInvoiceDirectory().getInvoiceList().add(invoice);
        customer.getMasterOrderList().addOrder(order);
        
        for(OrderItem oi : customer.getCart().getOrderItemList()){
            
            OrderRequest orderRequest = new OrderRequest();
            orderRequest.setOrderItem(oi);
            orderRequest.setOrdered(true);
            orderRequest.setOrderDate(new Date());
            orderRequest.setCustomer(userAccount);
            
           Supplier sup = orderRequest.getOrderItem().getProductInventory().getProduct().getProductCompany();
            sup.getWorkQueue().addWorkRequest((WorkRequest)orderRequest);
            userAccount.getWorkQueue().addWorkRequest((WorkRequest)orderRequest);
            amazon.getWorkQueue().addWorkRequest(orderRequest);
            oi.getProductInventory().setQuantity(-oi.getQuantity());
            
         
        
        }
        
        
        
        
        
        customer.getCart().getOrderItemList().clear();
        populateCart();
        
    }//GEN-LAST:event_checkOutJButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.remove(this);
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CheckoutCartTable;
    private javax.swing.JTextField CityTxtField;
    private javax.swing.JTextField StateTxtField;
    private javax.swing.JButton backButton;
    private javax.swing.JButton checkOutJButton;
    private javax.swing.JTextField countryTxtField;
    private javax.swing.JTable finalcheckoutJTable;
    private javax.swing.JTextField grandTotalTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField streetTxtfield;
    private javax.swing.JTextField taxTxtField;
    private javax.swing.JTextField totalCosttxtField;
    private javax.swing.JTextField zipCodetxtField;
    // End of variables declaration//GEN-END:variables
}
