/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.CustomerRole;

import EcoSystem.BankAccount.BankAccount;
import EcoSystem.Customer.Customer;
import EcoSystem.EcoSystem;
import EcoSystem.Enterprise.Amazon;
import EcoSystem.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Mustansir
 */
public class CustomerWorkArea extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem ecoSystem;
    private Amazon amazon;
    private UserAccount userAccount;
    private Customer customer;
    
    
    public CustomerWorkArea(JPanel upc , EcoSystem ecoSystem , Amazon amazon,UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = upc ;
        this.ecoSystem = ecoSystem;
        this.amazon = amazon;
        this.userAccount = userAccount;
        for(Customer cus : amazon.getCustomerDirectory().getCustomerList()){
            if(cus.getPerson().equals(userAccount.getPerson())){
                this.customer = cus;
            }
        }
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orderProduct = new javax.swing.JButton();
        trackProductJButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        orderProduct.setText("Order Products");
        orderProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderProductActionPerformed(evt);
            }
        });

        trackProductJButton.setText("Track Products");
        trackProductJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trackProductJButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Manage Finance ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("View Orders");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(orderProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(trackProductJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(orderProduct)
                .addGap(29, 29, 29)
                .addComponent(trackProductJButton)
                .addGap(43, 43, 43)
                .addComponent(jButton1)
                .addGap(30, 30, 30)
                .addComponent(jButton2)
                .addContainerGap(67, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void orderProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderProductActionPerformed
        OrderProductJPanel opjp = new OrderProductJPanel(ecoSystem, userProcessContainer, customer, amazon, userAccount);
        CardLayout layout =(CardLayout)userProcessContainer.getLayout();
        userProcessContainer.add("OrderProduct", opjp);
        layout.next(userProcessContainer);
    }//GEN-LAST:event_orderProductActionPerformed

    private void trackProductJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trackProductJButtonActionPerformed
        TrackProductJPanel tpjp = new TrackProductJPanel(userAccount, userProcessContainer);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.add("track", tpjp);
        layout.next(userProcessContainer);
    }//GEN-LAST:event_trackProductJButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
                ManageBankAccountJPanel manageBankAccountJPanel = new ManageBankAccountJPanel(userProcessContainer, customer, ecoSystem, amazon);
                CardLayout layout = (CardLayout)userProcessContainer.getLayout();
                userProcessContainer.add("Manage Bank Account",manageBankAccountJPanel);
                layout.next(userProcessContainer);                
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       ViewOrdersJPanel viewOrdersJPanel = new ViewOrdersJPanel(ecoSystem, userProcessContainer, customer, userAccount, amazon);
       CardLayout layout = (CardLayout)userProcessContainer.getLayout();
                userProcessContainer.add("view Orders ",viewOrdersJPanel);
                layout.next(userProcessContainer);      
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton orderProduct;
    private javax.swing.JButton trackProductJButton;
    // End of variables declaration//GEN-END:variables
}
