/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.CustomerRole;

import EcoSystem.BankAccount.BankAccount;
import EcoSystem.Customer.Customer;
import EcoSystem.EcoSystem;
import EcoSystem.Enterprise.Amazon;
import EcoSystem.Enterprise.Bank;
import EcoSystem.Enterprise.Enterprise;
import EcoSystem.Enterprise.Enterprise.EnterpriseType;
import EcoSystem.GeoConverting.AddressConverter;
import EcoSystem.Network.Network;
import EcoSystem.Person.Address;
import EcoSystem.Person.Person;
import EcoSystem.Role.CustomerRole;
import EcoSystem.UserAccount.UserAccount;
import EcoSystem.UserAccount.ValidateUserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.text.JTextComponent;

/**
 *
 * @author Mustansir
 */
public class NewCustomerJPanel extends javax.swing.JPanel {

    
    private JPanel userProcessContainer;
    private EcoSystem ecoSystem;
    public NewCustomerJPanel( JPanel upc , EcoSystem ecoSystem) {
        initComponents();
        
        this.userProcessContainer = upc;
        this.ecoSystem = ecoSystem;
        populateCountryCombo();
        
    }
    
    public void populateCountryCombo(){
        countryComboBox.removeAllItems();
        for(Network countryNetwork : ecoSystem.getNetworkDirectory().getNetworkList()){
            countryComboBox.addItem(countryNetwork);
        }
    }
    
    public void populatestateCombo(){
        Network countryNetwork = (Network)countryComboBox.getSelectedItem();
        if(countryNetwork == null){
            return;
        }
       
       
        
        stateComboBox.removeAllItems();
        for(Network stateNetwork : countryNetwork.getNetworkDirectory().getNetworkList()){
            stateComboBox.addItem(stateNetwork);
        }
    }
    
    public void populatecityCombo(){
        Network stateNetwork = (Network)stateComboBox.getSelectedItem();
        if(stateNetwork == null){
            return;
        }
        cityComboBox.removeAllItems();
        for(Network cityNetwork : stateNetwork.getNetworkDirectory().getNetworkList()){
            cityComboBox.addItem(cityNetwork);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstNameTxtField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        passwordTxtField = new javax.swing.JTextField();
        agetxtField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        stateComboBox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        createCustomerJButton = new javax.swing.JButton();
        cityComboBox = new javax.swing.JComboBox();
        zipCodetxtField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        streetTxtField = new javax.swing.JTextField();
        userNameTxtField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lastNameTxtField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        countryComboBox = new javax.swing.JComboBox();

        jLabel9.setText("City");

        jLabel10.setText("State");

        jLabel7.setText("Password");

        jLabel5.setText("Age");

        stateComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        stateComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateComboBoxActionPerformed(evt);
            }
        });

        jLabel6.setText("User Name");

        createCustomerJButton.setText("Create");
        createCustomerJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCustomerJButtonActionPerformed(evt);
            }
        });

        cityComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Please Provide Customer Details");

        jLabel3.setText("First Name");

        jLabel11.setText("Please Provide Address");

        jLabel13.setText("ZipCode");

        jLabel4.setText("Last Name");

        jLabel8.setText("Street Address:");

        backButton.setText("<< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel12.setText("Country");

        countryComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        countryComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel11)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(agetxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(firstNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lastNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(userNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(passwordTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(createCustomerJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(streetTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(countryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(zipCodetxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(160, 160, 160))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(firstNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lastNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(agetxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(streetTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(countryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(stateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(zipCodetxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(userNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(passwordTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createCustomerJButton)
                    .addComponent(backButton))
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void stateComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateComboBoxActionPerformed
        populatecityCombo();
    }//GEN-LAST:event_stateComboBoxActionPerformed

    private void createCustomerJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCustomerJButtonActionPerformed
        String firstName = firstNameTxtField.getText();
        String lastName = lastNameTxtField.getText();
        String Age = agetxtField.getText();
        String street = streetTxtField.getText();
        String city = String.valueOf(cityComboBox.getSelectedItem());
        String state = String.valueOf(stateComboBox.getSelectedItem());
        String country = String.valueOf(countryComboBox.getSelectedItem());
        String zipcode = zipCodetxtField.getText();
        String username = userNameTxtField.getText();
        String password = passwordTxtField.getText();
        
        for (Component C : this.getComponents()){
            if (C instanceof JTextField || C instanceof JTextArea ){
                String text =((JTextComponent) C).getText();
                if(text.trim().isEmpty()){
                    JOptionPane.showMessageDialog(null, "Please Complete the form");
                    return;                    
                }
            }            
        }
            
       
       
        
              
        
        Person person = ecoSystem.getPersonDirectory().createAndAddPerson();
        person.setFirstName(firstName);
        person.setLastName(lastName);
        person.setAge(Integer.parseInt(Age));
        Address add = new Address();
        add.setStreetAddress(street);
        add.setCity(city);
        add.setState(state);
        add.setCountry(country);
        add.setZipCode(Integer.parseInt(zipcode));
        AddressConverter ac = new AddressConverter();
        add.setLatitude(Double.parseDouble(ac.calculatelatitude(String.valueOf(add))));
        add.setLongitude(Double.parseDouble(ac.calculateLongitude(String.valueOf(add))));
        person.setAddress(add);
        
        Amazon amazon = null;
        Bank bank = null;
        
        
        for(Network network : ecoSystem.getNetworkDirectory().getNetworkList()){
        if(network.getName().equals(country)){
            for(Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()){
                if(e.getEnterpriseType().equals(EnterpriseType.Amazon)){
                    amazon = (Amazon)e;
                  
                }
                if(e.getEnterpriseType().equals(EnterpriseType.Bank)){
                    bank = (Bank)e;
                }
            }
        }
    }
        BankAccount bk = bank.getBankAccountDirectory().createandAddBankAccount();
        bk.setPerson(person);
        bk.setBankBalance(10000);
        ValidateUserAccount.validate(ecoSystem, username);
        Customer customer = amazon.getCustomerDirectory().createandAddCustomer();
        customer.setPerson(person);
        

        UserAccount ua = amazon.getUserAccountDirectory().createandAddUserAccount();
        ua.setUserName(username);
        ua.setPassword(password);
        ua.setPerson(person);
        ua.setRole(new CustomerRole());

    }//GEN-LAST:event_createCustomerJButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        userProcessContainer.removeAll();
        userProcessContainer.add(new JPanel());
       ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
       
    }//GEN-LAST:event_backButtonActionPerformed

    private void countryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryComboBoxActionPerformed
        populatestateCombo();
    }//GEN-LAST:event_countryComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField agetxtField;
    private javax.swing.JButton backButton;
    private javax.swing.JComboBox cityComboBox;
    private javax.swing.JComboBox countryComboBox;
    private javax.swing.JButton createCustomerJButton;
    private javax.swing.JTextField firstNameTxtField;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastNameTxtField;
    private javax.swing.JTextField passwordTxtField;
    private javax.swing.JComboBox stateComboBox;
    private javax.swing.JTextField streetTxtField;
    private javax.swing.JTextField userNameTxtField;
    private javax.swing.JTextField zipCodetxtField;
    // End of variables declaration//GEN-END:variables
}
