/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.CustomerRole;

import EcoSystem.BankAccount.BankAccount;
import EcoSystem.BankAccount.Transaction;
import EcoSystem.Customer.Customer;
import EcoSystem.EcoSystem;
import EcoSystem.Enterprise.Amazon;
import EcoSystem.Enterprise.Bank;
import EcoSystem.Enterprise.Enterprise;
import EcoSystem.Enterprise.Enterprise.EnterpriseType;
import EcoSystem.Network.Network;
import EcoSystem.Order.Invoice;
import EcoSystem.Order.OrderItem;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mustansir
 */
public class ProcessPayementJPanel extends javax.swing.JPanel {
    
    
    
    private Invoice invoice;
    private Customer customer ;
    private JPanel userProcessContainer;
    private Amazon amazon;
    private EcoSystem ecosystem;
    private BankAccount bankAccount;
    
    public ProcessPayementJPanel(Invoice invoice, Customer customer , JPanel upc , Amazon amazon , EcoSystem ecoSystem , BankAccount bankAccount) {
        initComponents();
        this.invoice = invoice;
        this.customer = customer;
        this.userProcessContainer = upc ;
        this.amazon = amazon;
        this.ecosystem = ecoSystem;
        this.bankAccount = bankAccount;
        populateform();
        populateTable();
    }
    
    private void populateTable(){
        DefaultTableModel model = (DefaultTableModel)ordertable.getModel();
        model.setRowCount(0);
        for(OrderItem oi : invoice.getOrder().getOrderItemList()){
           Object[] row =new Object[5];
           row[0]=oi.getProductInventory().getProduct().getName();
           row[1]=oi.getProductInventory().getProduct().getProductCompany();
           row[2]=oi.getProductInventory().getProduct().getProductPrice();
           row[3]=oi.getQuantity();
           row[4]=oi.Price();
           model.addRow(row);            
        }
    }
    
    private void populateform(){
        
        
        double  cost =0;
        for(OrderItem oi :invoice.getOrder().getOrderItemList()){
            cost +=oi.Price();
        }
        subtotaltxtField.setText(String.valueOf(cost));
        taxltxtField1.setText(String.valueOf(invoice.getTax()));
        grandtotaltxtField2.setText(String.valueOf(invoice.getTotal()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        ordertable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        subtotaltxtField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        taxltxtField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        grandtotaltxtField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        amountpaidTxtField = new javax.swing.JTextField();
        payButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        ordertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Product Name", "ProductCompany", "ProductPrice", "Quantity", "Price"
            }
        ));
        jScrollPane2.setViewportView(ordertable);

        jLabel1.setText("SubTotal :");

        subtotaltxtField.setEditable(false);

        jLabel2.setText("Tax :");

        taxltxtField1.setEditable(false);

        jLabel3.setText("Grand Total :");

        grandtotaltxtField2.setEditable(false);

        jLabel4.setText("Amount Being Paid :");

        amountpaidTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountpaidTxtFieldActionPerformed(evt);
            }
        });

        payButton.setText("Pay");
        payButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payButtonActionPerformed(evt);
            }
        });

        backButton.setText("<< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(amountpaidTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(payButton))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(grandtotaltxtField2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(taxltxtField1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(subtotaltxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(subtotaltxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(taxltxtField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(grandtotaltxtField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(amountpaidTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(payButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void amountpaidTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountpaidTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountpaidTxtFieldActionPerformed

    private void payButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payButtonActionPerformed
       try{
        double amount = Double.parseDouble(amountpaidTxtField.getText());
        double total = Double.parseDouble(grandtotaltxtField2.getText());
        if(amount != total){
            JOptionPane.showMessageDialog(null, "Please pay Exact Amount" );
            return;
        }
        invoice.setPaid(true);
        invoice.getPayment().setAmountPaid(amount);
        
        
        Bank bank = null;
        
        
        for(Network countryNetwork : ecosystem.getNetworkDirectory().getNetworkList()){
            if(countryNetwork.getName().equals(customer.getPerson().getAddress().getCountry())){
                for(Enterprise enterprise : countryNetwork.getEnterpriseDirectory().getEnterpriseList()){
                    if(enterprise.getEnterpriseType().equals(EnterpriseType.Bank)){
                        bank = (Bank)enterprise;
                    }
                }
            }
        }
        
        BankAccount credit = null;
        BankAccount debit = bankAccount;
        for(BankAccount bk : bank.getBankAccountDirectory().getBankAccountList()){
            if(bk.getEnterprise() != null){
              if(bk.getEnterprise().equals(amazon)){
                credit = bk;
            }  
            }
            
        }
        Transaction transaction = new Transaction();
        transaction.setAmount(amount);
        transaction.setCreditAccount(credit);
        transaction.setDebitAccount(debit);
        transaction.setType("Order Payment");
        bank.getBankAccountDirectory().performtransaction(transaction);
        credit.getTransactionList().add(transaction);
        debit.getTransactionList().add(transaction);
        
        
        
       }catch(NumberFormatException e) {JOptionPane.showMessageDialog(null, "Please enter only Numeric Data"); return;}
       
    }//GEN-LAST:event_payButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.remove(this);
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountpaidTxtField;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField grandtotaltxtField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable ordertable;
    private javax.swing.JButton payButton;
    private javax.swing.JTextField subtotaltxtField;
    private javax.swing.JTextField taxltxtField1;
    // End of variables declaration//GEN-END:variables
}
