/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.CustomerRole;

import EcoSystem.Customer.Customer;
import EcoSystem.Enterprise.Amazon;
import EcoSystem.Order.Order;
import EcoSystem.Order.OrderItem;
import EcoSystem.UserAccount.UserAccount;
import EcoSystem.WorkQueue.OrderReturnRequest;
import EcoSystem.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mustansir
 */
public class ReturnOrderJPanel extends javax.swing.JPanel {

    private Customer customer;
    private Amazon amazon;
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    public ReturnOrderJPanel(Customer customer , Amazon amazon , JPanel userProcessContainer , UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.amazon = amazon;
        this.customer = customer;
        this.userAccount = userAccount;
        populateOrderItemTable();
    }
    
    private void populateOrderItemTable(){
        DefaultTableModel model = (DefaultTableModel)orderItemJtable.getModel();
        model.setRowCount(0);
        for(Order order : customer.getMasterOrderList().getOrderList()){
            for(OrderItem orderItem : order.getOrderItemList()){
                Object[] row = new Object[3];
                row[0]=orderItem;
                row[1]=orderItem.getProductInventory().getProduct().getProductCompany();
                row[2]=orderItem.getQuantity();
                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        orderItemJtable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        orderItemJtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Product", "Product Company", "Quantity"
            }
        ));
        jScrollPane1.setViewportView(orderItemJtable);

        jButton1.setText("View Product ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        backButton.setText("<< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 5, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(backButton))
                .addContainerGap(122, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.remove(this);
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int selectedRow = orderItemJtable.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select an OrderItem");
        }
        OrderItem orderItem = (OrderItem )orderItemJtable.getValueAt(selectedRow, 0);
        for(WorkRequest wr : userAccount.getWorkQueue().getWorkQueueList()){
            if(wr instanceof OrderReturnRequest){
                OrderReturnRequest orr = (OrderReturnRequest)wr;
                if(orr.getOrderItem().equals(orderItem)){
                    JOptionPane.showMessageDialog(null, "The Order has Already been request for return . Please check its status");
                    return;
                }
            }
        }
        
        ViewProductJPanel viewProductJPanel = new ViewProductJPanel(userAccount, userProcessContainer, customer, amazon, orderItem);
        CardLayout layout =(CardLayout)userProcessContainer.getLayout();
        userProcessContainer.add("ViewProduct", viewProductJPanel);
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable orderItemJtable;
    // End of variables declaration//GEN-END:variables
}
