/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.CustomerRole;

import EcoSystem.EcoSystem;
import EcoSystem.UserAccount.UserAccount;
import EcoSystem.WorkQueue.OrderReturnRequest;
import EcoSystem.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mustansir
 */
public class ViewStatusJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private EcoSystem ecoSystem;
    
    public ViewStatusJPanel(UserAccount userAccount , JPanel upc , EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = upc;
        this.userAccount = userAccount;
        this.ecoSystem = ecoSystem;
        populateTable();
    }
    
    
    
    private void populateTable (){
        DefaultTableModel model = (DefaultTableModel)returnrequesttable.getModel();
        model.setRowCount(0);
        for(WorkRequest wr : userAccount.getWorkQueue().getWorkQueueList()){
            if(wr instanceof OrderReturnRequest){
                OrderReturnRequest orr = (OrderReturnRequest)wr;
                Object[] row = new Object[4];
                row[0]=orr;
                row[1]=orr.getOrderItem().getProductInventory().getProduct().getProductCompany();
                row[2]=orr.getOrderItem().getQuantity();
                row[3]=orr.getStatus();
                model.addRow(row);
            }
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        returnrequesttable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        returnrequesttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Product", "Product Supplier", "Quantity", "Status"
            }
        ));
        jScrollPane1.setViewportView(returnrequesttable);

        jButton1.setText("Drop Off Accepted Return");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(146, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int selectedRow = returnrequesttable.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select and order to return");
            return;
        }
        OrderReturnRequest orr = (OrderReturnRequest)returnrequesttable.getValueAt(selectedRow, 0);
        if(orr.getStatus().equalsIgnoreCase("Approved") ){
            DropOffProduct dropOffProduct = new DropOffProduct(userProcessContainer, userAccount, orr , ecoSystem);
            CardLayout layout  =(CardLayout)userProcessContainer.getLayout();
            userProcessContainer.add("Drop off Product",dropOffProduct );
            layout.next(userProcessContainer);
            
        }
        else if (orr.getStatus() == null){
            JOptionPane.showMessageDialog(null, "The request is still pending");
            return;
        }
        else if (orr.getStatus().equals("Package Droped Off")) {
            JOptionPane.showMessageDialog(null, "The Packed has been droped off at usps");
            return;
        }
        else{
            JOptionPane.showMessageDialog(null, "The request has been rejected");
            return;
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable returnrequesttable;
    // End of variables declaration//GEN-END:variables
}
