/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.CustomerRole;

import EcoSystem.Customer.Customer;
import EcoSystem.Enterprise.Amazon;
import EcoSystem.Order.OrderItem;
import EcoSystem.UserAccount.UserAccount;
import EcoSystem.WorkQueue.OrderRequest;
import EcoSystem.WorkQueue.OrderReturnRequest;
import EcoSystem.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Mustansir
 */
public class ViewProductJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Customer customer;
    private Amazon amazon;
    private OrderItem orderItem;
    private UserAccount userAccount;
    private OrderRequest orderRequest;
    public ViewProductJPanel(UserAccount userAccount ,JPanel userProcessContainer , Customer customer , Amazon amazon , OrderItem orderItem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.customer = customer ;
        this.amazon = amazon;
        this.orderItem = orderItem;
        this.userAccount = userAccount;
        populateform();
    }
    
    
    private void populateform(){
        productNametxtField.setText(String.valueOf(orderItem.getProductInventory().getProduct()));
        productCompnayTxtField.setText(String.valueOf(orderItem.getProductInventory().getProduct().getProductCompany()));
        productPricetxtField.setText(String.valueOf(orderItem.getProductInventory().getProduct().getProductPrice()));
        productQuantityTxtField.setText(String.valueOf(orderItem.getQuantity()));
      
        SpinnerNumberModel model = (SpinnerNumberModel)returnedQuantityJSpinner.getModel();
        model.setMaximum(orderItem.getQuantity());
        
        for(WorkRequest wr : userAccount.getWorkQueue().getWorkQueueList()){
            if(wr instanceof OrderRequest){
                OrderRequest or = (OrderRequest)wr;
                if(or.getOrderItem().equals(orderItem)){
                    productPurchaseDateTxtField.setText(String.valueOf(or.getOrderDate()));
                    deliveryDateTxtField.setText(String.valueOf(or.getDeliveryDate() == null ?"In Transit":or.getDeliveryDate()));
                    orderRequest= or;
                    break;
                }
            }
        }
           
                
            
        
    }
    
    
   
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        productNametxtField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        productCompnayTxtField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        productQuantityTxtField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        productPricetxtField = new javax.swing.JTextField();
        productPurchaseDateTxtField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        deliveryDateTxtField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        returnedQuantityJSpinner = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();

        jLabel1.setText("Product :");

        productNametxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productNametxtFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Product Company :");

        productCompnayTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productCompnayTxtFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Product Quantity :");

        productQuantityTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productQuantityTxtFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("Product Price :");

        productPricetxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productPricetxtFieldActionPerformed(evt);
            }
        });

        productPurchaseDateTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productPurchaseDateTxtFieldActionPerformed(evt);
            }
        });

        jLabel5.setText("Product Purchase Date :");

        jButton1.setText("Request Product Retun :");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        deliveryDateTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliveryDateTxtFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("Product Delivered Date :");

        backButton.setText("<< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        returnedQuantityJSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        jLabel7.setText("Quantity to be Returned");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2))
                                        .addGap(14, 14, 14))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(productCompnayTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(productNametxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(productQuantityTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(productPricetxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(productPurchaseDateTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deliveryDateTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(returnedQuantityJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(backButton)
                        .addGap(54, 54, 54)
                        .addComponent(jButton1)))
                .addContainerGap(198, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(productNametxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(productCompnayTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productQuantityTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productPricetxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(productPurchaseDateTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deliveryDateTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returnedQuantityJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(backButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void productNametxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productNametxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productNametxtFieldActionPerformed

    private void productCompnayTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productCompnayTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productCompnayTxtFieldActionPerformed

    private void productQuantityTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productQuantityTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productQuantityTxtFieldActionPerformed

    private void productPricetxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productPricetxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productPricetxtFieldActionPerformed

    private void productPurchaseDateTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productPurchaseDateTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productPurchaseDateTxtFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if(deliveryDateTxtField.getText().equalsIgnoreCase("In Transit"))
       {
           JOptionPane.showMessageDialog(null, "The Order Has Not Been Delivered as Yet ");
           return;       
       }
       int quantity =(int)returnedQuantityJSpinner.getValue();
       OrderReturnRequest orderReturnRequest = new OrderReturnRequest();
       OrderItem oi = new OrderItem();
       oi.setProductInventory(orderReturnRequest.getOrderItem().getProductInventory());
       oi.setQuantity(quantity);
       
       orderReturnRequest.setOrderItem(oi);
       orderReturnRequest.setPurchaseDate(orderRequest.getOrderDate());
       orderReturnRequest.setReturnRequestDate(new Date());
       orderReturnRequest.setSender(userAccount);
       
       
       amazon.getWorkQueue().addWorkRequest(orderReturnRequest);
       userAccount.getWorkQueue().addWorkRequest(orderReturnRequest);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void deliveryDateTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliveryDateTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deliveryDateTxtFieldActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.remove(this);
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextField deliveryDateTxtField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField productCompnayTxtField;
    private javax.swing.JTextField productNametxtField;
    private javax.swing.JTextField productPricetxtField;
    private javax.swing.JTextField productPurchaseDateTxtField;
    private javax.swing.JTextField productQuantityTxtField;
    private javax.swing.JSpinner returnedQuantityJSpinner;
    // End of variables declaration//GEN-END:variables
}
