/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.SupplierPackagingRole;

import EcoSystem.EcoSystem;
import EcoSystem.Enterprise.Supplier;
import EcoSystem.Organization.Organization;
import EcoSystem.UserAccount.UserAccount;
import EcoSystem.WorkQueue.OrderRequest;
import EcoSystem.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mustansir
 */
public class SupplierPackagingEmployeeWorkArea extends javax.swing.JPanel {

    private Supplier supplier;
    private UserAccount userAccount;
    private Organization organization;
    private JPanel userProcessContainer;
    private EcoSystem ecoSystem;
    public SupplierPackagingEmployeeWorkArea(Supplier supplier , UserAccount userAccount , Organization organization , JPanel UserProcessContainer , EcoSystem ecoSystem) {
        initComponents();
        this.supplier = supplier;
        this.userAccount = userAccount;
        this.organization = organization;
        this.userProcessContainer = UserProcessContainer;
        this.ecoSystem = ecoSystem;
        populatePackagingJobTable();
        packagingJobTable.setAutoCreateRowSorter(true);
    }
    
   
    public void populatePackagingJobTable(){
        DefaultTableModel model = (DefaultTableModel)packagingJobTable.getModel();
        model.setRowCount(0);
        for(WorkRequest wr : supplier.getWorkQueue().getWorkQueueList()){
            if(wr instanceof OrderRequest){
                OrderRequest or = (OrderRequest)wr;
            Object[] row = new Object[6];
            row[0]=or;
            row[1]=or.getOrderItem().getProductInventory().getProduct().getProductCompany();
            row[2]=or.getOrderItem().getQuantity();
            row[3]=or.getOrderDate();
            row[4]=or.isPackaged() == false ? "Not Processes" : or.getPackageDate();
            row[5]=or.getPackagingEmployee() == null ? "Not assigned" : or.getPackagingEmployee();
            model.addRow(row);
            }
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code.
     * The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        packagingJobTable = new javax.swing.JTable();
        assignToMeButton = new javax.swing.JButton();
        prcoessorderButton = new javax.swing.JButton();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        packagingJobTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Product", "Product Company", "Quantity", "OrderDate", "Packaging Status", "Assigned To "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(packagingJobTable);

        assignToMeButton.setText("Assign to Me ");
        assignToMeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignToMeButtonActionPerformed(evt);
            }
        });

        prcoessorderButton.setText("Process For Pickup");
        prcoessorderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prcoessorderButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(assignToMeButton)
                        .addGap(18, 18, 18)
                        .addComponent(prcoessorderButton)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assignToMeButton)
                    .addComponent(prcoessorderButton))
                .addContainerGap(127, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void assignToMeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignToMeButtonActionPerformed
        int selectedRow = packagingJobTable.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a order to be assigned ");
        }
        
        OrderRequest or= (OrderRequest)packagingJobTable.getValueAt(selectedRow, 0);
        if(or.getPackagingEmployee() != null){
            JOptionPane.showMessageDialog(null, "The orderRequest has already been assigned to an employeee");
            return;
        }
        
        or.setPackagingEmployee(userAccount);
        populatePackagingJobTable();
    }//GEN-LAST:event_assignToMeButtonActionPerformed

    private void prcoessorderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prcoessorderButtonActionPerformed
        int selectedItem = packagingJobTable.getSelectedRow();
        if(selectedItem < 0){
            JOptionPane.showMessageDialog(null,"Please select a Job to be process");
            return;
        }
        OrderRequest or = (OrderRequest)packagingJobTable.getValueAt(selectedItem, 0);
        if(!or.getPackagingEmployee().equals(userAccount)){
            JOptionPane.showMessageDialog(null, "The order is not assigned to you ");
            return;
        }
        if(or.isPackaged()){
            JOptionPane.showMessageDialog(null, "The order is already Processed");
            return;
        }
        ProcessOrderItemJPanel processOrderItemJPanel = new ProcessOrderItemJPanel(userProcessContainer, or, ecoSystem, supplier, userAccount);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.add("Process order", processOrderItemJPanel);
        layout.next(userProcessContainer);
        
                
    }//GEN-LAST:event_prcoessorderButtonActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        populatePackagingJobTable();
    }//GEN-LAST:event_formComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignToMeButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable packagingJobTable;
    private javax.swing.JButton prcoessorderButton;
    // End of variables declaration//GEN-END:variables
}
