/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.AmazonReturnEmployeeRole;

import EcoSystem.Enterprise.Amazon;
import EcoSystem.UserAccount.UserAccount;
import EcoSystem.WorkQueue.OrderReturnRequest;
import EcoSystem.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mustansir
 */
public class ProcessReturn extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Amazon amazon;
    private UserAccount userAccount;    
    public ProcessReturn(Amazon amazon , UserAccount userAccount , JPanel upc) {
        initComponents();
        this.userProcessContainer = upc ;
        this.amazon = amazon ;
        this.userAccount = userAccount;
        populatetable();
    }
     private void populatetable(){
        DefaultTableModel model = (DefaultTableModel)returnRequestTable.getModel();
        model.setRowCount(0);
        for(WorkRequest wr : userAccount.getWorkQueue().getWorkQueueList()){
            if(wr instanceof OrderReturnRequest){
                OrderReturnRequest orr = (OrderReturnRequest)wr;
                Object[] row = new Object[6];
                row[0]=orr;
                row[1]=orr.getOrderItem().getProductInventory().getProduct().getProductCompany();
                row[2]=orr.getOrderItem().getQuantity();
                row[3]=orr.getPurchaseDate();
                row[4]=orr.getReturnRequestDate();
                row[5]=orr.getStatus() == null ? "Pending" : orr.getStatus();
                model.addRow(row);
            }
        }
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        returnRequestTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        returnRequestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Product", "Product Compnay", "Quantity", "Purchase Date", "Requested Return Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(returnRequestTable);

        jButton1.setText("Process Request");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        backButton.setText("<< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(backButton))
                .addContainerGap(120, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int selectedrow = returnRequestTable.getSelectedRow();
        if(selectedrow < 0){
            JOptionPane.showMessageDialog(null, "Please select an request");
            return;
        }
        OrderReturnRequest orr = (OrderReturnRequest)returnRequestTable.getValueAt(selectedrow, 0);
        if(orr.getStatus() != null){
            JOptionPane.showMessageDialog(null, "The request has been processed");
            return;
        }
        returnSacntionJPanel sacntionJPanel = new returnSacntionJPanel(userProcessContainer, userAccount, amazon, orr);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.add("Sanction request",sacntionJPanel);
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
       populatetable();
    }//GEN-LAST:event_formComponentShown

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.remove(this);
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable returnRequestTable;
    // End of variables declaration//GEN-END:variables
}
