/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.AmazonReturnEmployeeRole;

import EcoSystem.DistanceCalculationGraph.DistanceAlgortihm;
import EcoSystem.Enterprise.Amazon;
import EcoSystem.Enterprise.WareHouse;
import EcoSystem.Network.Network;
import EcoSystem.Person.Address;
import EcoSystem.UserAccount.UserAccount;
import EcoSystem.WorkQueue.OrderReturn;
import EcoSystem.WorkQueue.OrderReturnRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JPanel;

/**
 *
 * @author Mustansir
 */
public class returnSacntionJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount ;
    private Amazon amazon ;
    private OrderReturnRequest orderReturnRequest;
    public returnSacntionJPanel(JPanel upc , UserAccount userAccount , Amazon amazon , OrderReturnRequest orderReturnRequest) {
        initComponents();
        this.userProcessContainer = upc ;
        this.userAccount = userAccount;
        this.amazon = amazon ;
        this.orderReturnRequest = orderReturnRequest;
        populateForm();
    }
    
    
    
    
    private void populateForm(){
        productNametxtField.setText(String.valueOf(orderReturnRequest.getOrderItem().getProductInventory().getProduct().getName()));
        productCompnayTxtField.setText(String.valueOf(orderReturnRequest.getOrderItem().getProductInventory().getProduct().getProductCompany()));
        productPricetxtField.setText((String.valueOf(orderReturnRequest.getOrderItem().getProductInventory().getProduct().getProductPrice())));
        productQuantityTxtField.setText(String.valueOf(orderReturnRequest.getOrderItem().getQuantity()));
        productPurchaseDateTxtField.setText(String.valueOf(orderReturnRequest.getPurchaseDate()));
        retrunDateTxtField.setText(String.valueOf(orderReturnRequest.getReturnRequestDate()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productCompnayTxtField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        retrunDateTxtField = new javax.swing.JTextField();
        productNametxtField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        productQuantityTxtField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        productPricetxtField = new javax.swing.JTextField();
        productPurchaseDateTxtField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        productCompnayTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productCompnayTxtFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Product Company :");

        jLabel6.setText("Product Return  Date :");

        retrunDateTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retrunDateTxtFieldActionPerformed(evt);
            }
        });

        productNametxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productNametxtFieldActionPerformed(evt);
            }
        });

        jLabel5.setText("Product Purchase Date :");

        jLabel1.setText("Product :");

        productQuantityTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productQuantityTxtFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("Product Price :");

        productPricetxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productPricetxtFieldActionPerformed(evt);
            }
        });

        productPurchaseDateTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productPurchaseDateTxtFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Product Quantity :");

        jButton1.setText("Approve For Return");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Reject");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        backButton.setText("<< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(14, 14, 14))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(productCompnayTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(productNametxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(productQuantityTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(productPricetxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(productPurchaseDateTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(retrunDateTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(backButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(productNametxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(productCompnayTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productQuantityTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productPricetxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(productPurchaseDateTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(retrunDateTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(backButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void productCompnayTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productCompnayTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productCompnayTxtFieldActionPerformed

    private void retrunDateTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retrunDateTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_retrunDateTxtFieldActionPerformed

    private void productNametxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productNametxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productNametxtFieldActionPerformed

    private void productQuantityTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productQuantityTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productQuantityTxtFieldActionPerformed

    private void productPricetxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productPricetxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productPricetxtFieldActionPerformed

    private void productPurchaseDateTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productPurchaseDateTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productPurchaseDateTxtFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        orderReturnRequest.setStatus("Approved");
        WareHouse nearestWarehouse = null;
       Address add =orderReturnRequest.getSender().getPerson().getAddress();
       double distance = 120000000;
       for(WareHouse wareHouse : amazon.getWarehouseDirectory().getWareHouseList()){
           double temp = DistanceAlgortihm.callocationdistance(add, wareHouse.getAddress());
           if(temp  < distance){
               distance = temp;
               nearestWarehouse = wareHouse;
           }
       }
      orderReturnRequest.setReturnWarehouse(nearestWarehouse);
      OrderReturn or = new OrderReturn();
      or.setCustomer(orderReturnRequest.getSender());
      or.setWareHouse(nearestWarehouse);
      or.setOrderItem(orderReturnRequest.getOrderItem());
      or.setSender(userAccount);
      or.setRequestDate(new Date());
      nearestWarehouse.getWorkQueue().addWorkRequest(or);
      orderReturnRequest.getSender().getWorkQueue().addWorkRequest(or);
      
      
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.remove(this);
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        orderReturnRequest.setStatus("Rejected");
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField productCompnayTxtField;
    private javax.swing.JTextField productNametxtField;
    private javax.swing.JTextField productPricetxtField;
    private javax.swing.JTextField productPurchaseDateTxtField;
    private javax.swing.JTextField productQuantityTxtField;
    private javax.swing.JTextField retrunDateTxtField;
    // End of variables declaration//GEN-END:variables
}
