/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.AmazonAdminRole;

import UserInterface.AmazonSupplierManagementEmployeeRole.ManageSupplierJPanel;
import EcoSystem.EcoSystem;
import EcoSystem.Enterprise.Amazon;
import EcoSystem.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Mustansir
 */
public class AmazonAdminWorkAreaJPanel extends javax.swing.JPanel {

    private EcoSystem ecoSystem;
    private JPanel userProcessContainer;
    private Amazon amazon;
    private UserAccount userAccount;
    public AmazonAdminWorkAreaJPanel(EcoSystem ecoSystem , JPanel upc , Amazon amazon,UserAccount userAccount) {
        initComponents();
        this.ecoSystem = ecoSystem;
        this.userProcessContainer = upc ;
        this.amazon = amazon;
        this.userAccount = userAccount;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageWareHouseJButton = new javax.swing.JButton();
        viewOrderStatusJButton = new javax.swing.JButton();
        viewFinanceJButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        manageWareHouseJButton.setText("Manage Warehouses");
        manageWareHouseJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageWareHouseJButtonActionPerformed(evt);
            }
        });

        viewOrderStatusJButton.setText("View Order Status");
        viewOrderStatusJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOrderStatusJButtonActionPerformed(evt);
            }
        });

        viewFinanceJButton.setText("Manage Finance");
        viewFinanceJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewFinanceJButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Manage Organization");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(manageWareHouseJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewOrderStatusJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewFinanceJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(manageWareHouseJButton)
                .addGap(18, 18, 18)
                .addComponent(viewOrderStatusJButton)
                .addGap(27, 27, 27)
                .addComponent(viewFinanceJButton)
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addContainerGap(99, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageWareHouseJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageWareHouseJButtonActionPerformed
        ManageWarehouseJPanel manageWarehouseJPanel = new ManageWarehouseJPanel(ecoSystem, amazon, userProcessContainer);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.add("ManageWarehouse", manageWarehouseJPanel);
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageWareHouseJButtonActionPerformed

    private void viewOrderStatusJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOrderStatusJButtonActionPerformed
        ViewMasterOrderListJPanel viewMasterOrderListJPanel = new ViewMasterOrderListJPanel(userProcessContainer, amazon);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.add("ManageSupplier", viewMasterOrderListJPanel);
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewOrderStatusJButtonActionPerformed

    private void viewFinanceJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewFinanceJButtonActionPerformed
        AmazonManageBankAccountJPanel amazonManageBankAccountJPanel = new AmazonManageBankAccountJPanel(userProcessContainer, ecoSystem, amazon);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.add("ManageFinance", amazonManageBankAccountJPanel);
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewFinanceJButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AmazonManageOrganizationJPanel amazonManageOrganizationJPanel = new AmazonManageOrganizationJPanel(amazon, userProcessContainer, ecoSystem, userAccount);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.add("ManageOrganization",amazonManageOrganizationJPanel);
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton manageWareHouseJButton;
    private javax.swing.JButton viewFinanceJButton;
    private javax.swing.JButton viewOrderStatusJButton;
    // End of variables declaration//GEN-END:variables
}
