/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.AmazonAdminRole;

import EcoSystem.EcoSystem;
import EcoSystem.Enterprise.Amazon;
import EcoSystem.Enterprise.WareHouse;
import EcoSystem.Network.Network;
import EcoSystem.Role.WarehouseAdmin;
import EcoSystem.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mustansir
 */
public class ManageWarehouseJPanel extends javax.swing.JPanel {

    private EcoSystem ecoSystem;
    private Amazon amazon;
    private JPanel userProcessContainer;
    public ManageWarehouseJPanel(EcoSystem ecoSystem , Amazon amazon ,JPanel upc) {
        
        initComponents();
        this.ecoSystem = ecoSystem;
        this.amazon = amazon;
        this.userProcessContainer = upc;
        populateLocationComboBox();
        
        
    }
    public void populateLocationComboBox(){
        locationComboBox.removeAllItems();
        locationComboBox.addItem("All States");
        Network inCountry = null;
        for(Network countryNetwork : ecoSystem.getNetworkDirectory().getNetworkList()){
            if(countryNetwork.getName().equals(amazon.getAddress().getCountry())){
            inCountry = countryNetwork;
            }            
        }
        for(Network stateNetwork :inCountry.getNetworkDirectory().getNetworkList()){
            locationComboBox.addItem(stateNetwork);
        }
    }
    public void populateWarehouseTable(String state){
        DefaultTableModel model = (DefaultTableModel)warehouseTable.getModel();
        model.setRowCount(0);
        for(WareHouse wareHouse : amazon.getWarehouseDirectory().getWareHouseList()){
            if(wareHouse.getAddress().getState().equals(state) || state.equalsIgnoreCase("All States")){
            Object[] row = new Object[3];
            row[0]=wareHouse;
            row[1]=wareHouse.getEnterpriseID();
            row[2]=wareHouse.getAddress();
            model.addRow(row);
            }
            
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        warehouseTable = new javax.swing.JTable();
        createWareHouseJButton = new javax.swing.JButton();
        createWareHouseAdminJButton = new javax.swing.JButton();
        locationComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        warehouseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Warehouse Name", "Warehouse ID", "Location"
            }
        ));
        jScrollPane1.setViewportView(warehouseTable);

        createWareHouseJButton.setText("Create Warehouse");
        createWareHouseJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createWareHouseJButtonActionPerformed(evt);
            }
        });

        createWareHouseAdminJButton.setText("Create WarehouseAdmin");
        createWareHouseAdminJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createWareHouseAdminJButtonActionPerformed(evt);
            }
        });

        locationComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        locationComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("Select Location :");

        BackButton.setText("<< Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BackButton)
                        .addGap(32, 32, 32)
                        .addComponent(createWareHouseJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(createWareHouseAdminJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(locationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createWareHouseJButton)
                    .addComponent(createWareHouseAdminJButton)
                    .addComponent(BackButton))
                .addContainerGap(109, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void locationComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationComboBoxActionPerformed
        Object obj = locationComboBox.getSelectedItem();
        if(obj == null){
            return;
        }
        String state = obj.toString();
        populateWarehouseTable(state);
    }//GEN-LAST:event_locationComboBoxActionPerformed

    private void createWareHouseJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createWareHouseJButtonActionPerformed
        CreateWarehouseJPanel createWarehouseJPanel = new CreateWarehouseJPanel(amazon, userProcessContainer, ecoSystem);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.add("createWarehouse", createWarehouseJPanel);
        layout.next(userProcessContainer);
    }//GEN-LAST:event_createWareHouseJButtonActionPerformed

    private void createWareHouseAdminJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createWareHouseAdminJButtonActionPerformed
        int selectRow = warehouseTable.getSelectedRow();
        if(selectRow < 0){
            JOptionPane.showMessageDialog(null, "Please Select a Warehouse");            
        }
        WareHouse wareHouse = (WareHouse)warehouseTable.getValueAt(selectRow, 0);
        for(UserAccount ua : wareHouse.getUserAccountDirectory().getUserAccountList()){
            if(ua.getRole() instanceof  WarehouseAdmin){
                JOptionPane.showMessageDialog(null, "An Admin for this WareHouse already exists");
                return;
            }
        }
        WarehouseAdminJPanel warehouseAdminJPanel = new WarehouseAdminJPanel(wareHouse, userProcessContainer, ecoSystem);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.add("WarehouseAdmin", warehouseAdminJPanel);
        layout.next(userProcessContainer);
    }//GEN-LAST:event_createWareHouseAdminJButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.remove(this);
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        Object obj = locationComboBox.getSelectedItem();
        if(obj == null){
            return;
        }
        String state = obj.toString();
        populateWarehouseTable(state);
    }//GEN-LAST:event_formComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton createWareHouseAdminJButton;
    private javax.swing.JButton createWareHouseJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox locationComboBox;
    private javax.swing.JTable warehouseTable;
    // End of variables declaration//GEN-END:variables
}
