/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.USPSAdminRole;

import EcoSystem.DeliveryVans.DeliveryVans;
import EcoSystem.EcoSystem;
import EcoSystem.Employee.Employee;
import EcoSystem.Enterprise.USPS;
import EcoSystem.Role.USPSDeliveryEmployeeRole;
import EcoSystem.UserAccount.UserAccount;
import EcoSystem.UserAccount.ValidateUserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Mustansir
 */
public class AssignDriverJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private USPS usps;
    private DeliveryVans deliveryVans;
    private EcoSystem ecosystem;
    public AssignDriverJPanel(JPanel upc , USPS usps , DeliveryVans deliveryVans , EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = upc ;
        this.usps = usps;
        this.deliveryVans = deliveryVans;
        this.ecosystem = ecoSystem;
        populateEmployeeCombo();
        
    }
    
    private void populateEmployeeCombo(){
        employeeCombo.removeAllItems();
        for(Employee employee : usps.getEmployeeDirectory().getEmployeeList()){
            employeeCombo.addItem(employee);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        employeeCombo = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userNameTxtField = new javax.swing.JTextField();
        passwordTxtField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        warningLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        jLabel1.setText("Employee :");

        employeeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        employeeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeComboActionPerformed(evt);
            }
        });

        jLabel2.setText("UserName :");

        jLabel3.setText("Password :");

        jButton1.setText("Assign");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        warningLabel.setForeground(new java.awt.Color(255, 0, 51));

        backButton.setText("<< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(userNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(employeeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(warningLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(passwordTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(backButton)
                        .addGap(96, 96, 96)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(warningLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(userNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passwordTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(backButton))
                .addContainerGap(123, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void employeeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeComboActionPerformed
        Employee employee = (Employee)employeeCombo.getSelectedItem();
        if(employee == null){
            return;
        }
        for(UserAccount ua : usps.getUserAccountDirectory().getUserAccountList()){
            if(ua.getPerson().equals(employee.getPerson())){
                if(ua.getRole() instanceof USPSDeliveryEmployeeRole){
                   warningLabel.setText("Employee is already Assigned to a Van");
                return ;
                }
                
            }
        }
        warningLabel.setText("");
    }//GEN-LAST:event_employeeComboActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Employee employee = (Employee)employeeCombo.getSelectedItem();
        for(UserAccount ua : usps.getUserAccountDirectory().getUserAccountList()){
            if(ua.getPerson().equals(employee.getPerson())){
                if(ua.getRole() instanceof USPSDeliveryEmployeeRole){
                   JOptionPane.showMessageDialog(null,"Please select another Employee ");
                return ;
                }
                
            }
        }
        
        String userName =userNameTxtField.getText();
        String password = passwordTxtField.getText();
        if(employee.equals(null) || userName.trim().isEmpty() || password.trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "please complete the form ");
            return;
        }
        ValidateUserAccount.validate(ecosystem, userName);
        UserAccount ua =usps.getUserAccountDirectory().createandAddUserAccount();
        ua.setUserName(userName);
        ua.setPassword(password);
        ua.setPerson(employee.getPerson());
        ua.setRole(new USPSDeliveryEmployeeRole());
        deliveryVans.setDriver(employee.getPerson());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.remove(this);
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JComboBox employeeCombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField passwordTxtField;
    private javax.swing.JTextField userNameTxtField;
    private javax.swing.JLabel warningLabel;
    // End of variables declaration//GEN-END:variables
}
