/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.AmazonBilllinEmployeeRole;

import EcoSystem.BankAccount.BankAccount;
import EcoSystem.BankAccount.Transaction;
import EcoSystem.EcoSystem;
import EcoSystem.Enterprise.Amazon;
import EcoSystem.Enterprise.Bank;
import EcoSystem.Enterprise.Supplier;
import EcoSystem.Order.Invoice;
import EcoSystem.Order.OrderItem;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mustansir
 */
public class AmazonProcessPayementJPanel extends javax.swing.JPanel {
    
    
    
    private Invoice invoice;    
    private JPanel userProcessContainer;
    private Amazon amazon;
    private EcoSystem ecosystem;
    private BankAccount bankAccount;
    private Bank bank;
    
    public AmazonProcessPayementJPanel(Invoice invoice, JPanel upc ,Bank bank , Amazon amazon , EcoSystem ecoSystem , BankAccount bankAccount) {
        initComponents();
        this.invoice = invoice;
        this.bank = bank;
        this.userProcessContainer = upc ;
        this.amazon = amazon;
        this.ecosystem = ecoSystem;
        this.bankAccount = bankAccount;
        populateform();
        populateTable();
    }
    
    private void populateTable(){
        DefaultTableModel model = (DefaultTableModel)ordertable.getModel();
        model.setRowCount(0);
        for(OrderItem oi : invoice.getOrder().getOrderItemList()){
           Object[] row =new Object[4];
           row[0]=oi.getProductInventory().getProduct().getName();
           row[1]=oi.getProductInventory().getProduct().getProductCompany();           
           row[2]=oi.getQuantity();
           row[3]=oi.Price();
           model.addRow(row);            
        }
    }
    
    private void populateform(){       
        
        
        grandtotaltxtField2.setText(String.valueOf(invoice.getTotal()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        ordertable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        grandtotaltxtField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        amountpaidTxtField = new javax.swing.JTextField();
        payButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        ordertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Product Name", "ProductCompany", "ProductPrice", "Quantity", "Price"
            }
        ));
        jScrollPane2.setViewportView(ordertable);

        jLabel3.setText("Grand Total :");

        grandtotaltxtField2.setEditable(false);

        jLabel4.setText("Amount Being Paid :");

        amountpaidTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountpaidTxtFieldActionPerformed(evt);
            }
        });

        payButton.setText("Pay");
        payButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payButtonActionPerformed(evt);
            }
        });

        backButton.setText("<< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(grandtotaltxtField2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(amountpaidTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(payButton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(backButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(grandtotaltxtField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(jLabel4))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(amountpaidTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(payButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(backButton)
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void amountpaidTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountpaidTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountpaidTxtFieldActionPerformed

    private void payButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payButtonActionPerformed
       try{
        double amount = Double.parseDouble(amountpaidTxtField.getText());
        double total = Double.parseDouble(grandtotaltxtField2.getText());
        if(amount != total){
            JOptionPane.showMessageDialog(null, "Please pay Exact Amount" );
            return;
        }
        invoice.setPaid(true);
        invoice.getPayment().setAmountPaid(amount);
        
        
       
        
        BankAccount credit = null;
        BankAccount debit = bankAccount;
        Supplier supplier = null;
        for(OrderItem oi : invoice.getOrder().getOrderItemList()){
            supplier=oi.getProductInventory().getProduct().getProductCompany();
            break;
        }
        for(BankAccount bk : bank.getBankAccountDirectory().getBankAccountList()){
            if(bk.getEnterprise() != null){
              if(bk.getEnterprise().equals(supplier)){
                credit = bk;
            }  
            }
            
        }
        Transaction transaction = new Transaction();
        transaction.setAmount(amount);
        transaction.setCreditAccount(credit);
        transaction.setDebitAccount(debit);
        transaction.setType("Supplier Payment");
        bank.getBankAccountDirectory().performtransaction(transaction);
        credit.getTransactionList().add(transaction);
        debit.getTransactionList().add(transaction);
        
        
        
       }catch(NumberFormatException e) {JOptionPane.showMessageDialog(null, "Please enter only Numeric Data"); return;}
       
    }//GEN-LAST:event_payButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.remove(this);
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountpaidTxtField;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField grandtotaltxtField2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable ordertable;
    private javax.swing.JButton payButton;
    // End of variables declaration//GEN-END:variables
}
