/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.AmazonBilllinEmployeeRole;

import EcoSystem.BankAccount.BankAccount;
import EcoSystem.EcoSystem;
import EcoSystem.Enterprise.Amazon;
import EcoSystem.Enterprise.Bank;
import EcoSystem.Enterprise.Enterprise;
import EcoSystem.Enterprise.Enterprise.EnterpriseType;
import EcoSystem.Network.Network;
import EcoSystem.Order.Invoice;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mustansir
 */
public class AmazonMakePaymentJpanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem ecoSystem;    
    private Amazon amazon;
    private BankAccount bankAccount;
    private Bank bank;
    
    
    public AmazonMakePaymentJpanel(JPanel upc , EcoSystem ecoSystem ,Amazon amazon ) {
        initComponents();
        this.userProcessContainer = upc ;
        this.ecoSystem = ecoSystem;        
        this.amazon = amazon;
        this.bankAccount = bankAccount;
        for(Network CountryNetwork : ecoSystem.getNetworkDirectory().getNetworkList()){
            if(CountryNetwork.getName().equals(amazon.getAddress().getCountry())){
                for(Enterprise enterprise : CountryNetwork.getEnterpriseDirectory().getEnterpriseList()){
                    if(enterprise.getEnterpriseType().equals(EnterpriseType.Bank)){
                        this.bank=(Bank)enterprise;
                        
                    }
                }
            }
        }
        for(BankAccount bk : this.bank.getBankAccountDirectory().getBankAccountList()){
            if(bk.getEnterprise() != null){
                if(bk.getEnterprise().equals(this.amazon)){
                    this.bankAccount=bk;
                }
                    
            }
        }
        populatePayment();
    }
    
    
    private void populatePayment(){
        DefaultTableModel model =(DefaultTableModel)paymentTable.getModel();
        model.setRowCount(0);
        
        for(Invoice invoice : amazon.getSupplierInvoiceDirectory().getInvoiceList()){
            Object[] row = new Object[4];
            row[0]=invoice;
            row[1]=invoice.getTotal();
            row[2]=invoice.getPayment().getAmountPaid();            
            row[3]=invoice.isPaid() == true ? "Amount Paid" : "Pending";
            model.addRow(row);
                    
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        paymentTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        paymentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Order", "Amount Due", "Amount paid", "isPaid"
            }
        ));
        jScrollPane1.setViewportView(paymentTable);

        jButton1.setText("Make Payment");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton1)
                .addContainerGap(129, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int selectedRow = paymentTable.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a order");
            return;
        }
        Invoice invoice = (Invoice)paymentTable.getValueAt(selectedRow, 0);
        if(invoice.isPaid()){
            JOptionPane.showMessageDialog(null, "Payment has Already Been made");
        }
        AmazonProcessPayementJPanel amazonProcessPayementJPanel = new AmazonProcessPayementJPanel(invoice, userProcessContainer, bank, amazon, ecoSystem, bankAccount);
        CardLayout layout = (CardLayout )userProcessContainer.getLayout();
        userProcessContainer.add("Amazon Process Payment ",amazonProcessPayementJPanel);
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        populatePayment();
    }//GEN-LAST:event_formComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable paymentTable;
    // End of variables declaration//GEN-END:variables
}
