/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.SystemAdminRole;

import EcoSystem.EcoSystem;
import EcoSystem.Network.Network;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mustansir
 */
public class CreateSubNetworksJPanel extends javax.swing.JPanel {

    private EcoSystem ecoSystem;
    private JPanel userProcessContainer;
    public CreateSubNetworksJPanel(EcoSystem ecoSystem , JPanel upc) {
        initComponents();
        this.ecoSystem = ecoSystem;
        this.userProcessContainer = upc;
        populateCountryCombobox();
    }
    
    public void populateCountryCombobox(){
        CountryComboBox.removeAllItems();
        for(Network n : ecoSystem.getNetworkDirectory().getNetworkList()){
            CountryComboBox.addItem(n);
        }
    }
    
    public void populateStateNetworks(Network network){
        DefaultTableModel model = (DefaultTableModel)stateTable.getModel();
        model.setRowCount(0);
        for(Network n : network.getNetworkDirectory().getNetworkList()){
            Object[] row = new Object[2];
            row[0]=n;
            row[1]= n.getNetworkId();
            
            model.addRow(row);
        }
    }
    
    public void populateCitynetworks(Network network){
        DefaultTableModel model = (DefaultTableModel)cityTable.getModel();
        model.setRowCount(0);
        for(Network n : network.getNetworkDirectory().getNetworkList()){
            Object[] row = new Object[2];
            row[0]=n;
            row[1]= n.getNetworkId();
            
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CountryComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        stateTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        stateNameTxtField = new javax.swing.JTextField();
        createStateNetworkJButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        cityTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        cityNameTxtField = new javax.swing.JTextField();
        createcCityNetworkJButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        CountryComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CountryComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CountryComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("Country Network");

        stateTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "State Network Name", "Network ID"
            }
        ));
        stateTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stateTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(stateTable);

        jLabel2.setText("State Name :");

        createStateNetworkJButton.setText("Create State Network");
        createStateNetworkJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createStateNetworkJButtonActionPerformed(evt);
            }
        });

        cityTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "City Network Name", "Network ID"
            }
        ));
        jScrollPane2.setViewportView(cityTable);

        jLabel3.setText("City Name :");

        createcCityNetworkJButton.setText("Create City Network");
        createcCityNetworkJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createcCityNetworkJButtonActionPerformed(evt);
            }
        });

        backButton.setText("<< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CountryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stateNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(createStateNetworkJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cityNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(createcCityNetworkJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backButton)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CountryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stateNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createStateNetworkJButton)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cityNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createcCityNetworkJButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CountryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CountryComboBoxActionPerformed
        Network countryNetwork = (Network )CountryComboBox.getSelectedItem();
        if(countryNetwork == null){
            return;
        }
        populateStateNetworks(countryNetwork);
        
    }//GEN-LAST:event_CountryComboBoxActionPerformed

    private void createStateNetworkJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createStateNetworkJButtonActionPerformed
        Network countryNetwork = (Network)CountryComboBox.getSelectedItem();
        if(countryNetwork == null){
            JOptionPane.showMessageDialog(null, "please select a Country Network");
            return;
        }
        String stateName = stateNameTxtField.getText();
        if(stateName.trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "please Enter the name of state to be entered");
            return;
            
        }
        countryNetwork.getNetworkDirectory().createandAddNetwork(stateName);
        populateStateNetworks(countryNetwork);
        
       
    }//GEN-LAST:event_createStateNetworkJButtonActionPerformed

    private void stateTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stateTableMouseClicked
       int selectedRow = stateTable.getSelectedRow();
       Network cityNetwork = (Network)stateTable.getValueAt(selectedRow, 0);
        populateCitynetworks(cityNetwork);
       
       
    }//GEN-LAST:event_stateTableMouseClicked

    private void createcCityNetworkJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createcCityNetworkJButtonActionPerformed
        int selectedRow = stateTable.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "please select State Network");
            return;
        }
       Network cityNetwork = (Network)stateTable.getValueAt(selectedRow, 0);
       String cityName = cityNameTxtField.getText();
       if(cityName.trim().isEmpty()){
           JOptionPane.showMessageDialog(null, "Please enter the name of the state to be entered ");
       }
       cityNetwork.getNetworkDirectory().createandAddNetwork(cityName);
        populateCitynetworks(cityNetwork);
    }//GEN-LAST:event_createcCityNetworkJButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
         CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.remove(this);
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CountryComboBox;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField cityNameTxtField;
    private javax.swing.JTable cityTable;
    private javax.swing.JButton createStateNetworkJButton;
    private javax.swing.JButton createcCityNetworkJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField stateNameTxtField;
    private javax.swing.JTable stateTable;
    // End of variables declaration//GEN-END:variables
}
