/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.SystemAdminRole;

import EcoSystem.EcoSystem;
import EcoSystem.Enterprise.Bank;
import EcoSystem.Enterprise.Enterprise;
import EcoSystem.Enterprise.Enterprise.EnterpriseType;

import EcoSystem.Network.Network;
import EcoSystem.Role.BankAdminRole;
import EcoSystem.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author Mustansir
 */
import javax.swing.table.DefaultTableModel;
public class ManageBankJPanel extends javax.swing.JPanel {

   private EcoSystem ecoSystem;
private JPanel userProcessContainer;
    public ManageBankJPanel(EcoSystem ecoSystem , JPanel upc) {
        initComponents();
        this.ecoSystem = ecoSystem;
        this.userProcessContainer = upc;
        populateBankTable();
    }

   
    
    public void populateBankTable()
    {
        ArrayList<Enterprise> BankList = new ArrayList<Enterprise>();
        for(Network network : ecoSystem.getNetworkDirectory().getNetworkList()){
            for(Enterprise enterprise :network.getEnterpriseDirectory().getEnterpriseList()){
                if(enterprise.getEnterpriseType().equals(EnterpriseType.Bank)){
                    BankList.add(enterprise);
                }
            }               
                
        }
        DefaultTableModel model = (DefaultTableModel)bankTable.getModel();
        model.setRowCount(0);
        for(Enterprise enterprise : BankList){
            Object[] row = new Object[2];
            row[0]= enterprise;
            row[1]= enterprise.getAddress().getCountry();
            model.addRow(row);
            
                    
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bankTable = new javax.swing.JTable();
        createHeadQuatersJButton = new javax.swing.JButton();
        createHeadQuaterAdminJButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        jButton1.setText("Create HeadQuaters");

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        jLabel1.setText("Amazon HeadQuaters ");

        bankTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Bank Name ", "Bank Location"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(bankTable);

        createHeadQuatersJButton.setText("Create a New Headquaters");
        createHeadQuatersJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createHeadQuatersJButtonActionPerformed(evt);
            }
        });

        createHeadQuaterAdminJButton.setText("Create Headquaters Administrator");
        createHeadQuaterAdminJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createHeadQuaterAdminJButtonActionPerformed(evt);
            }
        });

        backButton.setText("<< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backButton)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(createHeadQuaterAdminJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(createHeadQuatersJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(createHeadQuatersJButton)
                .addGap(18, 18, 18)
                .addComponent(createHeadQuaterAdminJButton)
                .addGap(28, 28, 28)
                .addComponent(backButton)
                .addGap(56, 56, 56))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createHeadQuatersJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createHeadQuatersJButtonActionPerformed
        CreateNewBankHeadquatersJPanel bankHeadquatersJPanel = new CreateNewBankHeadquatersJPanel(ecoSystem, userProcessContainer);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.add("Bank HeadQuaters" ,bankHeadquatersJPanel);
        layout.next(userProcessContainer);
    }//GEN-LAST:event_createHeadQuatersJButtonActionPerformed

    private void createHeadQuaterAdminJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createHeadQuaterAdminJButtonActionPerformed
        int selectedItem = bankTable.getSelectedRow();
        if(selectedItem < 0){
            JOptionPane.showMessageDialog(null,"Please Select an HeadQuaters");
            return;
        }
        
        Bank bank = (Bank)bankTable.getValueAt(selectedItem, 0);
        for(UserAccount ua : bank.getUserAccountDirectory().getUserAccountList()){
            if(ua.getRole() instanceof BankAdminRole){
                JOptionPane.showMessageDialog(null, "An Admin for this Bank Enterprise Already Exists");
                return;
            }
        }
        CreateBankAdminJPanel1 adminJPanel1 = new CreateBankAdminJPanel1(bank, userProcessContainer, ecoSystem);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.add("createBankAdmin",adminJPanel1);
        layout.next(userProcessContainer);
    }//GEN-LAST:event_createHeadQuaterAdminJButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.remove(this);
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        
    }//GEN-LAST:event_formFocusGained

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
         populateBankTable();        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTable bankTable;
    private javax.swing.JButton createHeadQuaterAdminJButton;
    private javax.swing.JButton createHeadQuatersJButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
