/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.USPSDeliveryRole;

import EcoSystem.DeliveryVans.DeliveryVans;
import EcoSystem.WorkQueue.OrderRequest;
import EcoSystem.WorkQueue.OrderReturn;
import EcoSystem.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mustansir
 */
public class DeliverOrderJPanel extends javax.swing.JPanel {

    private DeliveryVans deliveryVans;
    private JPanel userProcessContainer;
    public DeliverOrderJPanel(DeliveryVans deliveryVans , JPanel upc) {
        initComponents();
        this.userProcessContainer = upc ;
        this.deliveryVans = deliveryVans;
        populatedeliverTable();
    }
     private void populatedeliverTable(){
        DefaultTableModel model = (DefaultTableModel)deliveryJTable.getModel();
        model.setRowCount(0);
        
        for(WorkRequest wr : deliveryVans.getDeliveryQueue().getWorkQueueList()){
            
            if(wr instanceof OrderRequest){
                OrderRequest or = (OrderRequest)wr;
                Object[] row = new Object[5];
            row[0]=or;
            row[1]=or.getCustomer().getPerson().getAddress();
            row[2]=or.getShipmentDate();
            row[3]=or.isDelivered() == false ? "Not Delivered  " : or.getDeliveryDate();
            row[4]=or.getDeliveryEmployee() == null ? " Not assigned" : or.getDeliveryEmployee();
            
            model.addRow(row);
            }
            else if(wr instanceof OrderReturn){
                OrderReturn or = (OrderReturn)wr;
                Object[] row = new Object[5];
            row[0]=or;
            row[1]=or.getCustomer().getPerson().getAddress();
            row[2]=or.getCustomerDropOff();
            row[3]=or.getDeliveryDate() == null ? "Not Delivered  " : or.getDeliveryDate();
            row[4]=or.getDeliveryEmployee() == null ? " Not assigned" : or.getDeliveryEmployee();
            
            model.addRow(row);
            }
            
    
                    
            
        }  
            
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        deliveryJTable = new javax.swing.JTable();
        BackButton = new javax.swing.JButton();

        jButton1.setText("Deliver Order");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        deliveryJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Product", "Dellivery Address", "Shipment  Date", "Delivery Status", "Assigned to"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(deliveryJTable);

        BackButton.setText("<< Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(BackButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(BackButton))
                .addContainerGap(134, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int selectedItem = deliveryJTable.getSelectedRow();
        if(selectedItem < 0){
            JOptionPane.showMessageDialog(null, "Please select a order to be Delivered");
            return;
        }
        WorkRequest wr = (WorkRequest)deliveryJTable.getValueAt(selectedItem, 0);
        if(wr instanceof OrderRequest){
        OrderRequest or = (OrderRequest)deliveryJTable.getValueAt(selectedItem, 0);
        or.setDelivered(true);
        or.setDeliveryDate(new Date());    
        }
        else if (wr instanceof OrderReturn){
        OrderReturn or = (OrderReturn)deliveryJTable.getValueAt(selectedItem, 0);
        or.setDeliveryDate(new Date());
        
            
        }
        
        populatedeliverTable();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        userProcessContainer.remove(this);
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_BackButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JTable deliveryJTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
